package sistema.presentation.clientes;

import java.awt.Rectangle;
import java.io.IOException;
import java.util.Observable;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import sistema.logic.Cliente;

public class View extends javax.swing.JFrame implements java.util.Observer {

//**************  MVC ***********
    Controller controller;
    Model model;
    
    public void setController(Controller controller){
        this.controller=controller;
    }

    public Controller getController() {
        return controller;
    }
    
    public void setModel(Model model){
        this.model=model;
         model.addObserver(this);
    }

    public Model getModel() {
        return model;
    }
    
    @Override
    public void update(Observable o, Object arg) {
        Cliente cliente = model.getCliente();
        cedula.setText(cliente.getCedula());
        nombre.setText(cliente.getNombre());
        telefono.setText(cliente.getTelefono());
        int prov;
        if (cliente.getCedula().isEmpty()) prov=0;
        else prov=Integer.parseInt(cliente.getCedula().substring(0, 1));
        flag.setIcon(flags[prov]);
        clientes.setModel(new ClientesTableModel(model.getClientes()));
        
    }
//************** END MVC ***********
    
    public View() {
        initComponents();
        this.loadFlags();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        flag = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        listar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clientes");
        setMinimumSize(new java.awt.Dimension(600, 540));
        setPreferredSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("CEDULA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 15, 60, 20);

        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 61, 63, 20);

        jLabel3.setText("TELEFONO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 105, 79, 20);
        getContentPane().add(cedula);
        cedula.setBounds(117, 12, 166, 26);
        getContentPane().add(nombre);
        nombre.setBounds(117, 58, 207, 26);
        getContentPane().add(telefono);
        telefono.setBounds(117, 102, 146, 26);

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar);
        consultar.setBounds(301, 11, 99, 29);

        flag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(flag);
        flag.setBounds(334, 66, 207, 129);

        clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 520, 220);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(120, 150, 93, 29);

        listar.setText("Listar");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });
        getContentPane().add(listar);
        listar.setBounds(420, 10, 71, 29);

        regresar.setText("Regresar");
        regresar.setActionCommand("");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(393, 460, 130, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        controller.clienteGet(cedula.getText());
    }//GEN-LAST:event_consultarActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        controller.clienteSearch(cedula.getText());
    }//GEN-LAST:event_listarActionPerformed

    private void clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            controller.clienteEdit(clientes.getSelectedRow());
        }
    }//GEN-LAST:event_clientesMouseClicked

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        controller.clienteAdd(new Cliente(cedula.getText(),nombre.getText(),telefono.getText()));
    }//GEN-LAST:event_agregarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        controller.hide();
    }//GEN-LAST:event_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cedula;
    private javax.swing.JTable clientes;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel flag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listar;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

   int n=8;
   ImageIcon[] flags;        
    public void loadFlags() {
        flags = new ImageIcon[n];
        try {
            for(int p=0;p<n;p++) flags[p] = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("../flags/bandera"+p+".png"))); 
        } catch (IOException e) {
            System.err.println(e);
        }
    }  
}
